import java.util.ArrayList;

public class ManageStudents {
	/**
	 * Populates a sample ArrayList with 10 students.  The names and addresses were
	 * 	generated by https://mockaroo.com
	 * @return an ArrayList<Student> of 10 pre-generated student objects
	 * 
	 */
	public static ArrayList<Student> populateList() {
		ArrayList<Student> studentList = new ArrayList<Student>();
		
		// Random names and addresses generated using https://mockaroo.com 
		studentList.add(new Student(208, "Warner O'Hallihane", "29186 Mayfield Plaza"));
		studentList.add(new Student(203, "Anderea Simmers", "856 Riverside Crossing"));
		studentList.add(new Student(210, "Herold Attawell", "76578 Texas Lane"));
		studentList.add(new Student(205, "Arlyn Lidster", "2 Florence Trail"));
		studentList.add(new Student(202, "Alwyn Tumpane", "2 Farmco Point"));
		studentList.add(new Student(209, "Washington Cokayne", "1590 Kennedy Hill"));
		studentList.add(new Student(204, "Noreen Snarr", "29056 Mayfield Way"));
		studentList.add(new Student(201, "Maiga Spinley", "604 Coleman Hill"));
		studentList.add(new Student(206, "Gertruda Haig", "591 Burrows Court"));
		studentList.add(new Student(207, "Halie Arrol", "1995 Iowa Hill"));
		
		return studentList;
	}

	public static void main(String[] args) {
		ArrayList<Student> studentList = populateList();
		
		// Print unsorted student list
		System.out.println("Unsorted List of Students: ");
		for (int i = 0; i < studentList.size(); ++i) {
			studentList.get(i).printInfo();
			System.out.println();
		}
	}

}
